#!/bin/bash

. /etc/environment

# install SDK
wget -qO- "$ANDROID_SDK_URL" | tar -zx -C /opt

# install android addons, targets, etc
( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --all --filter platform-tools,$ANDROID_DEPENDENCIES
